name: Lootbox
main: david\lootbox\Loader
load: POSTWORLD
version: "3.0"
api: 5.0.0
authors:
  - David
description: Lootbox

permissions:
  lootbox.give:
    default: op
    description: Allows you to give lootboxes to players